Implementación lenguagechange InGame y MainMenu
Gotensfer/Taller-VI pull request #114
Opened 2022-11-06 07:56 UTC by jaydeeay

### Qué se hizo
Se hace la implementación del lenguaje y se agregan las banderas para este cambio, son botones solo queda darles su uso

Se hace la implementación del lenguaje en la escena de juego y también se modifican los prefabs de logros obtenidos.

Además se hace un corrección de un bug que hacía que se juntaran 2 tweeners en los tutos del rocket y pigeon

### Implementación:
Para la implementación de todo lo realizado es recomendado, muy recomendado usar las nuevas escenas que se tienen de **1.2 Implementación LenguageChange** y **1.2 Main menu LenguageChange**
De ser el caso contrario, entonces Copiar todos los siguientes elementos de la escena **1.2 Main menu LenguageChange** que son aquellos que son escenciales o cuentan con el TMP y su respectivo localizador para cambio de texto.

![image](https://user-images.githubusercontent.com/78647931/200160064-42c6d1bb-627d-4564-b81a-53376604a100.png)
![image](https://user-images.githubusercontent.com/78647931/200159992-993baf83-426e-43ab-a02f-4c32e8f8b132.png)

Y de la escena **1.2 Implementación LenguageChange**
![image](https://user-images.githubusercontent.com/78647931/200160138-8fd4f166-9ede-4590-8307-dba34163f21c.png)

Los prefabs para cuando se gana un logro quedan también cambiados cada uno.

DISCLAIMER: Si se quiere ahorrar tener que copiar cada elemento, organizarlo en la UI, chequear que quede correcto y que todo esté en orden y funcione. Ahh y que las referencias en el UIManager no se pierdan etc... Por eso dije anteriormente "es recomendado, muy recomendado usar las nuevas escenas"

2022-11-06 09:09 UTC, jaydeeay commented
![Giffi](https://user-images.githubusercontent.com/78647931/200160671-9b0a172b-27e0-4c56-a173-72d255e0215d.gif)


Todo funciona, aunque los objetos que se encuentran apagados por ejemplos los de tutoriales etc, únicamente cambian al darse la orgen al momento se encenderse (luego) es por esto que supongo el evento de cambio de idioma siempre va a estar en un update o realmente no sé como sería. Dejo el dato por aquí

2022-11-06 23:42 UTC, Gotensfer requested changes
Los botones de cambio de lenguaje no funcionan (?
Tal vez faltó agregar algo?

- Solucionar el que los botones de cambio de lenguaje no hagan nada

2022-11-06 23:47 UTC, jaydeeay commented
Qué los botones no hagan nada es intencional para que @Menguiza se encargue de implementar lo que haga que cambie el idioma teniendo en cuenta mi último comentario (los elementos apagados no se cambian el idioma si no hasta que se encienden)

2022-11-07 22:52 UTC, jaydeeay commented
Se hace la implementación de dos métodos ChangeToSpanish() y ChangeToEnglish() que están referenciados en los botones de cambio de idioma, aparentemente este cambio no estaba por esa razón no pude implementarlo anteriormente. 
![image](https://user-images.githubusercontent.com/78647931/200432427-643546e2-c971-47b7-98cf-6fd1f0a7e49f.png)

También se crea una variable  public static int Language que se encarga de hacer el cambio de idioma en un void OnEnable() implementado en el script de Localizacion, que lo que hace es chequear esta variable y al encenderse los objetos apagados, como los del tutorial ponerle la traducción. 
![image](https://user-images.githubusercontent.com/78647931/200432403-2daba2b3-683a-4553-883b-9e4adf4bb716.png)

2022-11-07 23:06 UTC, Gotensfer approved these changes
PR aceptado por motivos de tiempo y cuellos de botella en el repo.

2022-11-07 23:06 UTC, merged