Feature/player stop module
Gotensfer/Taller-VI pull request #4
Opened 2022-08-05 07:00 UTC by Menguiza

2022-08-05 15:39 UTC, Gotensfer commented on Assets/Scripts/PlayerStopModule.cs
> +    [SerializeField] private byte bounces = 3, bouncesUsed = 0;
Pilas pues, ¿Qué hablamos en la reunión sobre optimización? No use tipos de datos distintos de los genericos/bases (int, float, double, string, char) a menos de que estemos centrándonos en optimizaciones.

Cambie eso a un int, que si le paso esta luego le terminaré pasando las demás.

2022-08-05 15:41 UTC, Gotensfer commented on Assets/Scripts/PlayerStopModule.cs
> +        rb = GameObject.FindGameObjectWithTag("Player").GetComponent<Rigidbody2D>();//getplayer()
Es innecesario el uso de `FindGameObjectWithTag()` ya que esta clase se debería encontrar siempre en el player (Check el UML).

2022-08-05 15:44 UTC, Gotensfer commented on Assets/Scripts/PlayerStopModule.cs
> +    public void StopBounce()
Mientras que el método esta declarado, en ningún momento se implementa ni se llama al método.

2022-08-05 15:45 UTC, Gotensfer commented on Assets/Scripts/PlayerStopModule.cs
> +    void StopPlayer()
Mismo asunto que con el método StopBounce().

2022-08-05 15:52 UTC, Gotensfer commented on Assets/Scripts/PlayerStopModule.cs
> +public class PlayerStopModule : MonoBehaviour
La clase no se llama como está definido en el UML del proyecto.
![image](https://user-images.githubusercontent.com/77905732/183114614-c64ea7cc-daed-403c-a026-917efebc14d9.png)

Debería llamarse PlayerStop_Module

2022-08-05 16:11 UTC, Gotensfer requested changes
- Falta implementar los métodos, esto debería ocurrir en un `OnCollisionEnter2D()`
**_Disclaimer para futuras ocasiones:_** Mientras que el UML efectivamente no dice que la clase posee explicitamente un `OnCollisionEnter2D()` en este caso la clase podría requerir el uso de este método para poder implementar el método de `StopBounce()` (Y por ende, que esto prenda). los Métodos "ciclicos del motor de Unity" (No tengo el nombre en estos momentos) como `Update()`, `Start()`, `OnTriggerEnter()` y demás no estarán incluidos en el UML, ya que son métodos que ya poseen todas las clases que heredan de `Monobehaviour` y que son sujetas a uso de quien implemente la funcionalidad.

- La clase no se encuentra en Cacaleta/Player

![image](https://user-images.githubusercontent.com/77905732/183117633-a007e5b9-75c9-4e61-bd6c-0dfb28330872.png)

La clase debe de estar en el gameObject del player/cacaleta.
Por el otro lado, tampoco se encuentra en escena la clase, por lo que nunca fue implementado ni probado.

2022-08-12 02:38 UTC, Menguiza commented on Assets/Scripts/PlayerStopModule.cs
> +        rb = GameObject.FindGameObjectWithTag("Player").GetComponent<Rigidbody2D>();//getplayer()
![image](https://user-images.githubusercontent.com/79520727/184274754-9673bb8f-625a-43a9-ba17-d60786d0b523.png)
Ya se le agrego el script al player y se quito el findobjectwithtag()

2022-08-12 02:40 UTC, Menguiza commented on Assets/Scripts/PlayerStopModule.cs
> +public class PlayerStopModule : MonoBehaviour
![image](https://user-images.githubusercontent.com/79520727/184275026-8c594d0f-7120-4236-b71f-e30d17aeb5f7.png)

2022-08-12 02:45 UTC, Menguiza commented on Assets/Scripts/PlayerStopModule.cs
> +    public void StopBounce()
![image](https://user-images.githubusercontent.com/79520727/184275458-ff8f3407-0600-41ec-84b4-cdc6090ab1e4.png)

2022-08-12 02:45 UTC, Menguiza commented on Assets/Scripts/PlayerStopModule.cs
> +    void StopPlayer()
![image](https://user-images.githubusercontent.com/79520727/184275476-275e612a-03ce-4c63-8036-836630c7543f.png)
Siempre se llamo xD

2022-08-12 02:45 UTC, Menguiza commented on Assets/Scripts/PlayerStopModule.cs
> +    [SerializeField] private byte bounces = 3, bouncesUsed = 0;
![image](https://user-images.githubusercontent.com/79520727/184275517-547009c0-7da9-4035-94e9-3bfd60384024.png)

2022-08-12 03:00 UTC, Gotensfer approved these changes
A tener en cuenta:
- Ocurre un pequeño "stutter" visual cuando la pelota para
No es un error relevante en estos momentos, más más mucho más adelante hay que arreglarlo.

Todo en orden.

2022-08-12 03:01 UTC, merged