Sliders
Gotensfer/Taller-VI pull request #41
Opened 2022-09-16 07:43 UTC by Menguiza

2022-09-16 18:53 UTC, Gotensfer requested changes
Si, no estoy como reviewer, pero es mi responsabilidad revisar todo lo que dev haga xd

Se debe quitar del commit las modificaciones hechas a `MilkyNice SDF.asset` y `MilkyNice-Clean SDF.asset`. Tras ello se puede aceptar el PR

2022-09-16 20:06 UTC, Menguiza commented
Creo que ya

2022-09-16 21:26 UTC, Gotensfer commented
Negativo, ahora quitaste los sliders y solo dejaste los assets de Font xD

2022-09-18 18:36 UTC, Gotensfer approved these changes
Todo en orden! Quedo genial

2022-09-18 18:36 UTC, merged