Feature/distance tracker module
Gotensfer/Taller-VI pull request #5
Opened 2022-08-05 07:00 UTC by Menguiza

2022-08-05 16:26 UTC, Gotensfer commented on Assets/Scripts/DistanceTracker.cs
> +
Cuando la clase BaseTracker_Module esté definida e implementada, se requiere el uso del atributo `RequiereComponent(typeof())` para cumplir con la dependencia establecida en el UML

2022-08-05 16:28 UTC, Gotensfer commented on Assets/Scripts/DistanceTracker.cs
> +    private float _distance = 0f;
Falta el campo público de `travelledDistance` especificado en el UML.

2022-08-05 16:31 UTC, Gotensfer commented on Assets/Scripts/DistanceTracker.cs
> +    string TrackPlayerDistance(Vector2 currentPos)
Tras un testeo se encuentra que el jugador registra 0.2m de distancia constantemente sin haberlo lanzado, por ahora no es un problema importante pero se debe de calibrar o ajustar el código para compensar.

2022-08-05 16:34 UTC, Gotensfer commented on Assets/Scripts/DistanceTracker.cs
> +        Debug.Log(TrackPlayerDistance(player.position));//getPlayer()
`GetPlayer()` no debería ser llamado acá, puesto que la referencia del `transform` ya la obtuviste en el `Start()`, así como lo tienes en esta linea ya está, no hay necesidad de llamar el método más adelante.

2022-08-05 16:36 UTC, Gotensfer commented on Assets/Scripts/DistanceTracker.cs
> +public class DistanceTracker : MonoBehaviour
La clase no tiene el nombre especificado en el UML
![image](https://user-images.githubusercontent.com/77905732/183121908-52f359f0-b109-4b46-8765-f3af8fafef8b.png)

Debería llamarse DistanceTracker_Module

2022-08-05 16:45 UTC, Gotensfer commented on Assets/Scripts/DistanceTracker.cs
> +
Falta el método público de `CalculateTravelledDistance()`.

2022-08-05 17:02 UTC, Gotensfer requested changes
![image](https://user-images.githubusercontent.com/77905732/183122398-decd2950-c82f-4f4d-a9fc-b6264e316803.png)

La escena de TrackerBaseModule posee lo que supongo era la clase `Tracker_BaseModule`, sin embargo se encuentra _missing_, No debería estar esta escena incompleta en el PR de distance tracker (?

- La clase no posee el nombre especificado en el UML.

La clase debe de llamarse `DistanceTracker_Module`.

- La clase no posee ni implementa el campo público de `travelledDistance`.

La clase debe de tener declarado e implementado este campo público, ya que con esto es que otras clases se comunicarán con la información de este tracker. No cumple con el UML.

- La clase no posee ni implementa el método público de `CalculateTravelledDistance()`.

La clase debe de tener declarado e implementado este método público quien se encarga de realizar periódiacamente el cálculo de la distancia recorrida por el jugador y ponerlo en el campo de `travelledDistance`. No cumple con el UML.

2022-08-05 19:14 UTC, Menguiza commented on Assets/Scripts/DistanceTracker.cs
> +    string TrackPlayerDistance(Vector2 currentPos)
Ese error no es mi culpa, posicionaron mal el jugador XD  entonces cuando se snapea fuera del suelo registra una pequeña distancia.

2022-08-12 02:13 UTC, Menguiza commented on Assets/Scripts/DistanceTracker.cs
> +        Debug.Log(TrackPlayerDistance(player.position));//getPlayer()
Es que no insinuaba llamarlo, solo dejaba claro que la informacion saldria de alli.

2022-08-12 02:13 UTC, Menguiza commented on Assets/Scripts/DistanceTracker.cs
> +public class DistanceTracker : MonoBehaviour
![image](https://user-images.githubusercontent.com/79520727/184272423-6af9fadc-3d3a-4a0e-8dd8-b02bb6336c5c.png)
Ya se llama como debe.

2022-08-12 02:15 UTC, Menguiza commented on Assets/Scripts/DistanceTracker.cs
> +    string TrackPlayerDistance(Vector2 currentPos)
![image](https://user-images.githubusercontent.com/79520727/184272580-605980d9-c652-4d7a-bd0b-e301bc757b5d.png)
Para solucionar eso puse una sobrecarga en el metodo para ingresar un offset de ser necesario.

2022-08-12 02:18 UTC, Menguiza commented on Assets/Scripts/DistanceTracker.cs
> +    private float _distance = 0f;
![image](https://user-images.githubusercontent.com/79520727/184272843-cb8ecf33-bd9a-4999-98f3-a9e773a0be13.png)
Renombre la variable y la hice accesible pero no cambiable.

2022-08-12 02:19 UTC, Menguiza commented on Assets/Scripts/DistanceTracker.cs
> +
Esto debe de hacerse al integrar, mientras no estemos en ese paso, no creo que haya problema dejándolo asi.

2022-08-12 02:28 UTC, Menguiza commented on Assets/Scripts/DistanceTracker.cs
> +
![image](https://user-images.githubusercontent.com/79520727/184273774-6480dd87-a5bd-45d5-ba32-8215b4424d49.png)
Ya el metodo es public, tambien su sobrecarga y tienen el nombre esparado

2022-08-12 02:44 UTC, Gotensfer commented on Assets/Scripts/DistanceTracker_Module.cs
> +        Debug.Log(TrackPlayerDistance(Vector2.zero, player.position));//getPlayer()
El método `TrackPlayerDistance` ya no existe, debe de cambiarse por `CalculateTravelledDistance`

2022-08-12 02:45 UTC, Gotensfer requested changes
![image](https://user-images.githubusercontent.com/77905732/184275465-90d79684-b639-4ba3-882d-38f494faab16.png)
- Debe de reemplazarse el método por `CalculateTravelledDistance`

2022-08-12 02:48 UTC, Menguiza commented on Assets/Scripts/DistanceTracker_Module.cs
> +        Debug.Log(TrackPlayerDistance(Vector2.zero, player.position));//getPlayer()
Que guevonada, eso ya se habia cambiado. No se me guardo el cambio del script. Hpta!!!
![image](https://user-images.githubusercontent.com/79520727/184275802-1143a1e7-8b92-4581-b095-1a7906e4ce17.png)

2022-08-12 02:54 UTC, Gotensfer requested changes
- La distancia está tomando en cuenta la altura
Debería de estar tomando la distancia horizontal.

2022-08-12 03:15 UTC, Gotensfer approved these changes
Todo en orden.

2022-08-12 03:21 UTC, merged