Funcionalidad
Gotensfer/Taller-VI pull request #72
Opened 2022-10-07 16:43 UTC by Menguiza

2022-10-10 08:31 UTC, jaydeeay reviewed
a

2022-10-10 20:22 UTC, jaydeeay requested changes
He probado el cohete y no me funciona lo touches. Haciéndolo o no es el mismo cambio en la velocidad.

Los cambios necesario están en comentarios dentro del código.

Porfa comenta lo que haces y lo que sucede en el código, no entiendo ni chimba

2022-10-10 20:22 UTC, jaydeeay commented on TallerVI Unity/Assets/Scripts/PowerUp_Rocket.cs
> +                    force += 2f;
Necesito parametrizar la fuerza que se suma por cada touch

2022-10-10 20:22 UTC, jaydeeay commented on TallerVI Unity/Assets/Scripts/PowerUp_Rocket.cs
> +            if (hitInformation.collider != null)
Si se toca cualquier parte del mundo, ¿Por qué un collider?

2022-10-14 14:28 UTC, Gotensfer commented
@Menguiza Esto generará un cuello de botella si no se resuelve pronto.

2022-10-17 22:16 UTC, Menguiza commented
![image](https://user-images.githubusercontent.com/79520727/196293539-96b3d3e9-3f35-486a-9a76-d5dea56a5412.png)

Ya se actualizó la función. Antes era requerido tocar al personaje, ahora se puede tocar la pantalla en cualquier zona. Tambien se prametrizo la fuerza a incrementar.

2022-10-20 08:31 UTC, jaydeeay approved these changes
Lo he probado y funciona

El incrementador de velocidad se debe aumentar para que sea notable. Con 2 no es muy notable el cambio en la velocidad al tap

2022-10-20 08:33 UTC, jaydeeay commented
Recomiendo hacer merge con developmente para actualizar la rama y evitar posibles conflictos. Aunque el merge se puede realizar

2022-10-20 13:31 UTC, Gotensfer approved these changes
¡Buen trabajo!

2022-10-20 13:31 UTC, merged